/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include<stdint.h>
#include<stdio.h>

/* This function executes in THREAD MODE of the processor */
void generate_interrupt()
{
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//enable IRQ3 interrupt
	*pISER0 |= ( 1 << 3);//when we try to access this system register in unpriv access level, we will get a hardfault

	//generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF);

}

void change_access_level_unpriv(void)
{

	//read
	__asm volatile ("MRS R0,CONTROL");//moving the content of CONTROL to r0
	//modify
	__asm volatile ("ORR R0,R0,#0x01");//OR operation of r0 and 0x01
	//write
	__asm volatile ("MSR CONTROL,R0"); //moving the content of r0 to CONTROL
	//setting the 0th bit of the CONTROL register to 1 , so the thread mode access level
	//is unprivilaged

}

/* This function executes in THREAD MODE+ PRIV ACCESS LEVEL of the processor */
int main(void)
{
	//In thread mode : before interrupt

	change_access_level_unpriv(); //changing thread mode access level to unprivilaged

	generate_interrupt();

	//In thread mode : after interrupt

	for(;;);
}

/* This function(ISR) executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode : ISR\n");
}

void HardFault_Handler(void)  //runs in handler mode
{
	printf("Hard fault detected\n");
	while(1);
}
