/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	//The first 1MB of SRAM (0x20000000 to 0x200FFFFF)
	//The first 1MB of Peripheral (0x40000000 to 0x400FFFFF)
	//Both are bit-banding or bit-addressable regions
	//We have unique addresses for each bits in those regions known as Alias address
	//General formula =>
	//Alias address = (alias_base) + (32 * (bit_band_memory_addr - bit_band_base)) + (bit * 4)
//                     0x22000000	        Given address where    starting region    bit position
//                     for SRAM             we need to find the    of bit-banding-    where we need to
//                                          alias address          0x20000000 for     find the alias
//                                                                 SRAM               address

// example :  find the alias address for the 0th bit of location- 0x20000000
// alias address = (0x22000000) + (32 * (0x20000000 - 0x20000000)) + (0 * 4)
//  =  0x22000000
// should use ldrb or strb instruction with the alias address to use the bit-banding
//or use byte pointer (same as ldrb or strb)



	__asm volatile("ldr r0 , =#0x2200001C     ") ;
	__asm volatile("ldr r1 , =#0x01     ") ;
	__asm volatile ("strb r1 , [r0]         ");

	uint8_t * p =  (uint8_t *)  0x22000024      ;
	*p  =   (uint8_t) 0  ;

	for(;;);
}
