/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include "led.h"
#include "main.h"


void init_systick_timer(uint32_t tick_hz){
	uint32_t * pSRVR =  (uint32_t*) 0xE000E014     ; //systick reload value register
	uint32_t * pSCSR =  (uint32_t*) 0xE000E010     ; //systick control and status register


	uint32_t count_value =   ( (16000000U) / (tick_hz) )  - 1  ;
	//uint32_t count_value =   16777215 ;


	*pSRVR  &=  ~(0x00FFFFFF)      ;
	*pSRVR  |=    count_value ;

	*pSCSR |=  (1 << 1) ; //enables systick exception request
	*pSCSR |=  (1 << 2) ; //uses processor clock source

	*pSCSR |=  (1 << 0) ; //enables the systick timer , enables the counter


}

//uint32_t x ;
__attribute__((naked))void init_scheduler_stack_msp ( uint32_t msp_val       ){
	__asm volatile("msr  msp ,  r0  ");
	__asm volatile("bx lr");
}

//uint32_t psp_of_tasks[4] = {T1_STACK , T2_STACK , T3_STACK , T4_STACK } ;
/*
uint32_t tasks[4] =  {
		(uint32_t)task1_handler ,
		(uint32_t)task2_handler ,
		(uint32_t)task3_handler ,
		(uint32_t)task4_handler
} ;
*/


TCB_t user_tasks[5] ; //IDLE task , T1 , T2 , T3 , T4

uint32_t current_task = 1 ;  //task1 initially
uint32_t g_tick_count = 0 ;

void idle_task(){
	while(1);
}


void init_tasks_stack(){

	for(int x = 0 ;  x < 5 ; x++  ){
		user_tasks[x].current_state = TASK_RUNNING_STATE ;
	}

	user_tasks[0].psp_value = IDLE_STACK ;
	user_tasks[1].psp_value = T1_STACK ;
	user_tasks[2].psp_value = T2_STACK ;
	user_tasks[3].psp_value = T3_STACK ;
	user_tasks[4].psp_value = T4_STACK ;

	user_tasks[0].task_handler = (uint32_t)idle_task;
	user_tasks[1].task_handler = (uint32_t)task1_handler;
	user_tasks[2].task_handler = (uint32_t)task2_handler;
	user_tasks[3].task_handler = (uint32_t)task3_handler;
	user_tasks[4].task_handler = (uint32_t)task4_handler;


	uint32_t * pPSP ;

	for(int i = 0 ;   i<5 ; i++ ){    //from idle_task to task4 initially


		pPSP =  (uint32_t*)  ( user_tasks[i].psp_value )   ;

		pPSP -- ;
		*pPSP =  0x01000000 ; //xPSR on the stack frame initially

		pPSP -- ;
		*pPSP =  user_tasks[i].task_handler ;   //PC on the stack frame initially

		pPSP -- ;
		*pPSP =  0 ;         //LR on the stack frame initially

		for(int j = 0  ;   j<13   ; j++    ){
			pPSP --  ;
			*pPSP =  0 ;   // GPRs R0-R12 on the stack frame initially
		}

		user_tasks[i].psp_value  =   (uint32_t)  pPSP ;

	}
}

void task_delay(uint32_t tick_count){   //input is in ms

	__asm volatile ("mov r0,#0x01");
	__asm volatile ("msr primask , r0 ");  //disabling all interrupts to avoid race conditions of
										   //thread mode and handler mode code



	if(current_task){
		user_tasks[current_task].block_count = g_tick_count + tick_count ;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE ;

		uint32_t * pICSR = (uint32_t*) 0xE000ED04   ;
		//Interrupt control and state register (register of SCB)
		*pICSR |=  (1 << 28) ; //pending the pendsv exception
	}

	__asm volatile ("mov r0,#0x00");
	__asm volatile ("msr primask , r0 "); //enabling the interrupts

}




int main(void)
{

	//setting the pendsv exception to the lowest possible priority
	//setting the systick exception to the highest priority
	uint32_t * pSHPR3 = (uint32_t*) 0xE000ED20 ;
	//system handler priority register 3
	*pSHPR3 =  0x00F00000 ;

//-----------------------------experimentation------------------------
	/*
	__asm volatile ("mov r0,#0x01");
	//__asm volatile ("msr primask , r0 ");  //disabling all interrupts

	uint32_t * pICSR = (uint32_t*) 0xE000ED04   ;
	//Interrupt control and state register (register of SCB)


	*pICSR |=  (1 << 26) ; //pending the systick exception

	*pICSR |=  (1 << 28) ; //pending the pendsv exception



	__asm volatile ("mov r0,#0x00");
	//__asm volatile ("msr primask , r0 "); //enabling the interrupts


	while(1);

*/

//------------------------------end of experimentation -------------------



	uint32_t * pSHCSR =  (uint32_t*) 0xE000ED24  ;
	//  system handler control and state register (SCB register)
		*pSHCSR  |=       (7 <<  16 )     ;
	//  enabling the mem , usage , bus fault exceptions



	init_scheduler_stack_msp(SCHED_STACK);

	init_tasks_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);


	register uint32_t registe0 __asm("r0") ;
	registe0 =   user_tasks[1].psp_value  ;
	__asm volatile("msr psp , r0   ");  //initialising psp with task1 private stack pointer
	__asm volatile("mov r0 , #0x02   ");
	__asm volatile("msr control , r0   "); //switching the sp to psp

	task1_handler();

    /* Loop forever */
	for(;;);
}

void task1_handler(void){
	while(1){
		//printf("Task1 \n");
		led_on(LED_GREEN);
		task_delay(3000) ;
		led_off(LED_GREEN);
		task_delay(1000) ;
	}
}

void task2_handler(void){
	while(1){
		//printf("Task2 \n");
		led_on(LED_ORANGE);
		task_delay(500) ;
		led_off(LED_ORANGE);
		task_delay(500) ;
	}
}

void task3_handler(void){
	while(1){
		//printf("Task3 \n");
		led_on(LED_BLUE);
		task_delay(250) ;
		led_off(LED_BLUE);
		task_delay(250) ;
	}
}

void task4_handler(void){
	while(1){
		//printf("Task4 \n");
		led_on(LED_RED);
		task_delay(125) ;
		led_off(LED_RED);
		task_delay(125) ;
	}
}

void save_psp_value(uint32_t  psp  ){
	user_tasks[current_task].psp_value =  psp  ;
}

void update_current_task(){
	int state = TASK_BLOCKED_STATE ;
	for(int i = 0  ;   i<5 ; i++  ){
		current_task++;
		current_task %= 5 ;
		state = user_tasks[current_task].current_state ;
		if (    (state == TASK_RUNNING_STATE  )   && (current_task != 0)      )
			break ;
	}

	if(state !=   TASK_RUNNING_STATE){
		current_task =  0 ;
	}
}

uint32_t get_psp_val(){
	return user_tasks[current_task].psp_value ;
}

__attribute__((naked))void PendSV_Handler(){

	//printf("pendsv--- \n");

	__asm volatile("push {lr}") ;


	__asm volatile("mrs r0 , psp ");
	__asm volatile("stmdb  r0! , {r4-r11}    ") ;
	__asm volatile("bl save_psp_value");


	__asm volatile("bl update_current_task");


	__asm volatile("bl get_psp_val");
	__asm volatile("ldmia  r0! ,  {r4-r11}   ") ;
	__asm volatile("msr psp , r0 ");



	__asm volatile("pop {lr}");
	__asm volatile("bx lr") ;


}


void SysTick_Handler(){
	//printf("systick----- \n");
	//x = x+1 ;
	//printf("%lu \n" , x );

	g_tick_count++ ;

	for(int i = 1 ;  i<5 ; i++  ){
		if(user_tasks[i].current_state  != TASK_RUNNING_STATE   ){
			if(user_tasks[i].block_count  == g_tick_count  ){
				user_tasks[i].current_state = TASK_RUNNING_STATE ;
			}
		}
	}


	uint32_t * pICSR = (uint32_t*) 0xE000ED04   ;
	//Interrupt control and state register (register of SCB)
	*pICSR |=  (1 << 28) ; //pending the pendsv exception


}

void HardFault_Handler(){
	while(1);
}

void MemManage_Handler(){
	while(1);
}

void BusFault_Handler(){
	while(1);
}

void UsageFault_Handler(){
	while(1);
}











