/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t * pISPR1 = (uint32_t *)0xE000E204; //address of ISPR 1 register (irq39 for usart3 periph set pending register)
	*pISPR1 =   (uint32_t )  0x00000080 ; //setting the bit 7 of the register(pending irq39 bit  , 39%32 == 7 )

	uint32_t * pISER1 = (uint32_t *)0xE000E104 ; //address of ISER 1 register (irq39 for usart3 periph set enable register)
	*pISER1 =   (uint32_t )  0x00000080 ;//setting the bit 7 of the register(setting irq39 bit  , 39%32 == 7 , enabling irq39 )



    /* Loop forever */
	for(;;);
}

void USART3_IRQHandler (){

	printf("IRQ39\n");


}
