/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void UsageFault_Handler_c(uint32_t* pBASE );


int main(void)
{


	uint32_t * pSHCSR =  (uint32_t*) 0xE000ED24  ;
//  system handler control and state register (SCB register)
	*pSHCSR  |=       (7 <<  16 )     ;
//  enabling the mem , usage , bus fault exceptions



	uint32_t * pSRAM =  (uint32_t*) 0x20010000  ; //random SRAM location
	*pSRAM =  0xFFFFFFFF ; //storing invalid instruction in that location
	void (*fptr)(void) = (void*) ( ( (uint32_t)pSRAM )  |   1     )   ;
	fptr(); //the value inside the fptr , i.e., 0x20010001 is loaded
	//into the PC (program counter) , so the instruction starts executing
	//from that address , which in this case has an invalid instruction
	//so the processor throws a fault






	while(1);
}


void HardFault_Handler(){
	int x = 5;
	x = x + 5;
}

void MemManage_Handler(){
	int x = 5;
	x = x + 5;
}

void BusFault_Handler(){
	int x = 5;
	x = x + 5;
}

__attribute__((naked)) void UsageFault_Handler(void){
	__asm volatile("mrs r0 ,   msp");
	__asm volatile("b UsageFault_Handler_c");
}


void UsageFault_Handler_c(uint32_t* pBASE ){
	printf("Usage Fault !!\n");
	printf("R0 : %lx\n"  ,   pBASE[0]         );
	printf("R1 : %lx\n"  ,   pBASE[1]         );
	printf("R2 : %lx\n"  ,   pBASE[2]         );
	printf("R3 : %lx\n"  ,   pBASE[3]         );
	printf("R12 : %lx\n"  ,   pBASE[4]         );
	printf("LR : %lx\n"  ,   pBASE[5]         );
	printf("PC : %lx\n"  ,   pBASE[6]         );
	printf("xPSR : %lx\n"  ,   pBASE[7]         );
	while(1);
}

