/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>




int main(void)
{



	__asm volatile("svc #0x99");
	register uint32_t register_5 __asm("r5");
	uint32_t val_modified = register_5 ;

	printf("The modified value is %lx \n" , val_modified      );



    /* Loop forever */
	for(;;);
}


__attribute__((naked)) void SVC_Handler(){
	__asm volatile("mrs r0,  msp  ");
	register uint32_t msp_val __asm("r0");
	uint32_t * pBASE = (uint32_t*) msp_val  ;
	uint32_t  svc_opcode_arg_addr =  (pBASE[6]  - 2 )   ;
	uint8_t arg_val  =   *((uint8_t*)svc_opcode_arg_addr)  ;


	__asm volatile("push {LR}");


	printf("SVC Argument value : %x \n"  ,   arg_val     );

	__asm volatile("pop {LR}");

	register uint32_t msp_val2 __asm("r5");
	msp_val2 = arg_val + 4 ;

	__asm volatile("bx lr") ;

	//while(1);


}



