/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

typedef unsigned int uint32_t ;



int main(void)
{
//                  ISPR0
	*((uint32_t*)(0xE000E200))  =   (uint32_t)  (0x00000003)                     ;
	//setting the pending bits for both irq0 and irq1 in ISPR0

//                  IPR0
	*((uint32_t*)(0xE000E400))  =   (uint32_t)  (0x00000010)          ;
//   configuring the priority for irq0 to 0x10  and  irq1 to 0   in IPR0

//                  ISER0
	*((uint32_t*)(0xE000E100))  =   (uint32_t)  (0x00000003)                     ;
	//Enabling the interrupts for both the irq 0 and 1



	//*((uint32_t*)(0xE000E100))  =   (uint32_t)  (0x00000002)                     ;



    /* Loop forever */
	for(;;);
}

void WWDG_IRQHandler(){
	int x =  5 ;
	x = x+ 3;

}

void PVD_IRQHandler(){

	int x = 10 ;
	x = x + 9 ;
}




