/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//Below all are CPU core registers
	__asm volatile("ldr r1 , =#0x20001000") ; //loading r1 with immediate value
	__asm volatile("ldr r2 , =#0x20001004") ; //loading r2 with immediate value
	__asm volatile("ldr r0 , [r1]") ; //loading r0 from the memory location address in r1 (SRAM in this case)
	__asm volatile("ldr r1 , [r2]") ; //loading r1 from the memory location address in r2 (SRAM in this case)
	__asm volatile("add r0 , r0 , r1 ") ; //add operation of r0 and r1 , result stored in r0
	__asm volatile("str r0 , [r2]") ; //storing r0 value into the memory location address in r2(SRAM in this case )


	//SRAM is a component block of the STM32(volatile memory) , starting from address 0x20000000


	int val = 0x50 ;
	__asm volatile ("mov r0, %0"  : :  "r"(val)  )  ; //mov the value of C variable "val" into r0

	__asm volatile ("mov r0, %0"  : :  "i"(0xabcd)  )  ; //mov the immediate value into r0


	uint32_t control_register ;
	__asm volatile("mrs %0, CONTROL" :    "=r"(control_register)    )  ;
	//using mrs instruction to move the content of special register - "CONTROL" into the C variable "control register"


	int v ;
	int * p =  (int*) 0x20000000      ;
	__asm volatile("ldr %0, [%1] "  :  "=r"(v)     : "r"(p)  )  ;
//Basically we are doing :
//	v = *p ;
//Pointer dereferencing


    /* Loop forever */
	for(;;);
}
